CXXFLAGS = `pkg-config --cflags playerc++` `pkg-config --cflags opencv` -g
CFLAGS = `pkg-config --cflags playerc` `pkg-config --cflags opencv` -g
LDLIBS = `pkg-config --libs playerc++` `pkg-config --libs opencv`
CC = g++

all: control
