CXXFLAGS = `pkg-config --cflags playerc++` `pkg-config --cflags opencv`
CFLAGS = `pkg-config --cflags playerc` `pkg-config --cflags opencv`
LDLIBS = `pkg-config --libs playerc++` `pkg-config --libs opencv`
CC = g++

all: control control_test
