CXXFLAGS = `pkg-config --cflags playerc++` `pkg-config --cflags opencv`
CFLAGS = `pkg-config --cflags playerc` `pkg-config --cflags opencv`
LDLIBS = `pkg-config --libs playerc++` `pkg-config --libs opencv`
CC = g++

all: control complete_global_map_access no_map_sharing limited_map_sharing

